### ISSUE TITLE
NPC sheet lacks the "profile-img" class on the avatar IMG tag

### ISSUE THREAD

**Issue by luxuryhoofs** [wintersleepAI/foundry-swnr#11]
Problem statement: the "character" sheet (character-sheet.html) has the class property of "profile-img" on the IMG tag of the character avatar:
```
      <img
        class="profile-img w-24 h-24 object-contain"
        src="{{actor.img}}"
        title="{{actor.name}}"
        data-edit="img"
      />
```

the NPC sheet (npc-sheet.html) lacks this property, and as such the Tokenizer module can't be used to create and assign tokens.

As a game master, I want to be able to use the Tokenizer module ( https://github.com/mrprimate/vtta-tokenizer/) to automatically create tokens for NPC sheets in the same way I can use the plugin on PC sheets.

Acceptance criteria:
- Users with permissions to edit character sheets can activate the Tokenizer module by clicking the avatar of a specific character sheet

**Comment by wintersleepAI** [comment]
should be fixed in the latest release
