### ISSUE TITLE
Rolltables Already included?

### ISSUE THREAD

**Issue by Leolele99** [wintersleepAI/foundry-swnr#20]
Hello,

more of a general feature request or question.
The Spice-King version recently included auto rolltables from the book, which was a long requested feature.
Is this already present within the newest release of this branch? Or will it come someday? 

Thank you for your great work here!

**Comment by wintersleepAI** [comment]
If it's in SK's branch it will be easy to include the next release (factions). This one is going a bit slower but hope to get out in the coming weeks. Should be able to include.

**Comment by Leolele99** [comment]
Will the new update be 0.8.X compatible too?

**Comment by aaronelmore** [comment]
it should be, but extra testing when i announce a test release would always be appreciated :)

**Comment by wintersleepAI** [comment]
new update will need testing on 0.8. but it should work

rollable tables will be included
