### ISSUE TITLE
NPC item issue

### ISSUE THREAD

**Issue by wintersleepAI** [wintersleepAI/foundry-swnr#21]
If I click "skill adds to damage" on an item assigned to a NPC, it doesn't roll. No error, it just does nothing. It does work on PCs. I'm thinking since NPCs do not have skills, that would be why it doesn't work. But they do have a trained skill attribute. Shouldn't that work in place of a typical PC skill?

**Comment by wintersleepAI** [comment]
This should be fixed in 0.6

**Comment by Cup-of-Coffee** [comment]
It appears to be have been resolved.

![Screenshot 2022-07-10 220836](https://user-images.githubusercontent.com/39238717/178175453-5788b042-72ce-4ec1-a4f6-c2b57d460075.png)

**Comment by wintersleepAI** [comment]
resolved
