### ISSUE TITLE
ST and Attack rolls not working in foundry 9.255

### ISSUE THREAD

**Issue by jerry2478** [wintersleepAI/foundry-swnr#23]
Foundry VTT | Retrieved and compiled template systems/swnr/templates/items/armor-sheet.html
handlebar-helpers.ts:36 {skillID: '', skillItem: undefined}
handlebar-helpers.ts:36 {skillID: '', skillItem: undefined}
handlebar-helpers.ts:36 {skillID: '', skillItem: undefined}
handlebar-helpers.ts:36 {skillID: '', skillItem: undefined}
foundry.js:3055 Foundry VTT | Rendering BaseSheet
character-sheet.ts:461 S.Event {originalEvent: PointerEvent, type: 'click', target: i.fas.fa-dice-d20, currentTarget: div.item.skill.skillRoll.w-32.flex-grow.space-y-1, isDefaultPrevented: ƒ, …}
skill.ts:9 Skill roll  SWNRSkill {apps: {…}, _sheet: null, parent: SWNRCharacterActor, pack: null, data: ItemData}
foundry.js:4662 Foundry VTT | Retrieved and compiled template systems/swnr/templates/dialogs/roll-skill.html
foundry.js:3055 Foundry VTT | Rendering ValidatedDialog
skill.ts:30 S.fn.init [div#app-51.app.window-app.swnr]
foundry.js:6771 
        
       Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.
evaluate @ foundry.js:6771
roll @ foundry.js:6874
_doRoll @ skill.ts:47
submit @ foundry.js:44072
submit @ ValidatedDialog.ts:46
_onClickButton @ foundry.js:44035
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
backend.mjs:306 Foundry VTT | Created ChatMessage with id [vrXEZikEZwATU6U4]
character-sheet.ts:200 S.Event {originalEvent: PointerEvent, type: 'click', target: div.save.sheet-button.gap-2, currentTarget: div.save.sheet-button.gap-2, isDefaultPrevented: ƒ, …}
foundry.js:4662 Foundry VTT | Retrieved and compiled template systems/swnr/templates/dialogs/roll-save.html
foundry.js:3055 Foundry VTT | Rendering ValidatedDialog
foundry.js:6771 
        
       Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.
evaluate @ foundry.js:6771
roll @ foundry.js:6874
_doRoll @ character-sheet.ts:221
submit @ foundry.js:44072
submit @ ValidatedDialog.ts:46
_onClickButton @ foundry.js:44035
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:44076 
        
       Uncaught Error: TypeError: Cannot read properties of undefined (reading 'total')
    at ValidatedDialog.submit (foundry.js:44076:13)
    at ValidatedDialog.submit (ValidatedDialog.ts:46:20)
    at ValidatedDialog._onClickButton (foundry.js:44035:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)
submit @ foundry.js:44076
submit @ ValidatedDialog.ts:46
_onClickButton @ foundry.js:44035
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:6771 
        
       Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.
evaluate @ foundry.js:6771
roll @ foundry.js:6874
_doRoll @ character-sheet.ts:221
submit @ foundry.js:44072
submit @ ValidatedDialog.ts:46
_onClickButton @ foundry.js:44035
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:44076 
        
       Uncaught Error: TypeError: Cannot read properties of undefined (reading 'total')
    at ValidatedDialog.submit (foundry.js:44076:13)
    at ValidatedDialog.submit (ValidatedDialog.ts:46:20)
    at ValidatedDialog._onClickButton (foundry.js:44035:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)
submit @ foundry.js:44076
submit @ ValidatedDialog.ts:46
_onClickButton @ foundry.js:44035
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
character-sheet.ts:200 S.Event {originalEvent: PointerEvent, type: 'click', target: i.fas.fa-dice-d20, currentTarget: div.save.sheet-button.gap-2, isDefaultPrevented: ƒ, …}
foundry.js:3055 Foundry VTT | Rendering ValidatedDialog
foundry.js:6771 
        
       Roll#evaluate is becoming asynchronous. In the short term you may pass async=true or async=false to evaluation options to nominate your preferred behavior.
evaluate @ foundry.js:6771
roll @ foundry.js:6874
_doRoll @ character-sheet.ts:221
submit @ foundry.js:44072
submit @ ValidatedDialog.ts:46
_onClickButton @ foundry.js:44035
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:44076 
        
       Uncaught Error: TypeError: Cannot read properties of undefined (reading 'total')
    at ValidatedDialog.submit (foundry.js:44076:13)
    at ValidatedDialog.submit (ValidatedDialog.ts:46:20)
    at ValidatedDialog._onClickButton (foundry.js:44035:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)

**Comment by Cup-of-Coffee** [comment]
I checked this on a fresh install for Foundry build 266. 

Attacks appear to be fully functional and fine, no such errors appeared.

**Comment by jerry2478** [comment]
Was using link from reddit, not the current build. sry I'm dumb.
