### ISSUE TITLE
 Add the quantity value to Weapons and Armor

### ISSUE THREAD

**Issue by Cup-of-Coffee** [wintersleepAI/foundry-swnr#25]
Currently the only way for a character sheet to hold several quantities of the same type of armor is to have multiple instances take up space. 

![Screenshot 2022-07-10 215527](https://user-images.githubusercontent.com/39238717/178174280-a561f272-6207-408e-bfb8-aa0e09f3eb46.png)

In the example above, you have a character holding three chaincutters, 3 combat field uniforms and 7 biofuel tanks. Unlike the biofuel tanks, you can only show a character having multiple items of the same the weapons and armor is to have it take up a significant amount of sheet space.

**Comment by wintersleepAI** [comment]
added
