### ISSUE TITLE
Unable to Add Characters to Starships

### ISSUE THREAD

**Issue by Cup-of-Coffee** [wintersleepAI/foundry-swnr#27]
The GM and Player is unable to add their character actor to the Starship Sheet. A error being given instead when they try.

![Screenshot 2022-10-08 083555](https://user-images.githubusercontent.com/39238717/194707946-924a58da-2a75-4132-8472-6bea858afac1.png)

This is on Foundry VTT version 10.287.

**Comment by Escvor** [comment]
Same problem in my case. Foundry VTT 10.287. Same error message.

Also actors cant be linked to drones. I guess this is related to this problem.

**Comment by giuseppe-crea** [comment]
I created a PR #29  to fix this issue.

**Comment by giuseppe-crea** [comment]
I have near zero knowledge of either Foundry or JS/TS, but tried my hand at a very simple fix for this issue now available in PR #30.

**Comment by wintersleepAI** [comment]
Will be resolved in the next release. Thanks @giuseppe-crea !
