### ISSUE TITLE
Drone and Ship Fittings intermingled (dev-1.0)

### ISSUE THREAD

**Issue by thebwt** [wintersleepAI/foundry-swnr#33]
Howdy! 

When we go to search for fittings to add to a drone sheet, we see the starship fittings as well.
![image](https://user-images.githubusercontent.com/578441/210131215-97db88b5-28a3-46a3-a86b-7a75e8fe1adf.png)

The inverse is true when adding them to ships
![image](https://user-images.githubusercontent.com/578441/210131247-20da5751-1ebc-4e8e-96a4-7260fe24f9db.png)

It's certainly not game-breaking by any means, but figured I'd file it away.

**Comment by thebwt** [comment]
I'm digging into this, I've gotten the styling fixed with a simple https://github.com/thebwt/foundry-swnr/commit/d408027bc168ad2f808faa6082c929a7a2b0949f

Working through limiting the fitting types to ones that match the actor type...

**Comment by thebwt** [comment]
I actually now hate that fix because it'd need top be applied to every select in the table... There's got to be  a more general way to do it.

**Comment by thebwt** [comment]
Back to the actual problem: fitting filtering
we actually have a data.type already in the model. I'm trying to see if that can be passed to the search thing as a filter, but i'm kinda worried about this ominous warning

> commons.js:1703 Error: You are accessing the SWNRDroneActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.

I'm worried because the fitting item model has a root level `type` of `shipFitting` and I'm betting we'll have a collision with the fancy subtype of `drone|mech|ship`

**Comment by thebwt** [comment]
okay think i've got this done in #34

**Comment by wintersleepAI** [comment]
The warning has to do with a major change in v10 of the data model. The old one is supported until v12 or v11, but it will complain a lot. Once the change is made though the system will not be compatible with v9. So waiting a little bit.

**Comment by wintersleepAI** [comment]
resolved in your PR!
