### ISSUE TITLE
Sheet doesn't handle small sizes very well

### ISSUE THREAD

**Issue by thebwt** [wintersleepAI/foundry-swnr#36]
Via Ramirez in Discord:
> When making sheet smaller, HP and Strain stats at the top get a little weird.

confirmed by dragging window to it's smallest size:
![image](https://user-images.githubusercontent.com/578441/210601295-28e43923-e541-4841-a1ca-965c2f921545.png)

**Comment by wintersleepAI** [comment]
I am not sure if I will consider this an issue, potentially a min width could be added. But at some small width I cant imagine any sheet having much utility
