### ISSUE TITLE
Add damage modifier to weapon rolls

### ISSUE THREAD

**Issue by thebwt** [wintersleepAI/foundry-swnr#39]
There are often situational bonuses, so the weapon attack roll should have  a misc damage modifier (like it already has for the attack roll)

**Comment by wintersleepAI** [comment]
Added the damage mod button on the apply damage button. I think this is a clean approach, especially with the "remember these settings" button on the roll and how that would be a little more complicated with a dmg mod. Holler if you disagree and we can explore more
