### ISSUE TITLE
Item description HTML fields no longer editable on v10

### ISSUE THREAD

**Issue by Notaveerus** [wintersleepAI/foundry-swnr#42]
The structure changes in v10 appear to have broken the description fields on all items. Existing descriptions display fine however making changes to the field result in the below error
`Uncaught (in promise) Error: undefined. data.description is not an active editor name!
[No packages detected]
    at BaseSheet.saveEditor (foundry.js:6060:46)
    at jR.save_onsavecallback (foundry.js:6102:39)
    at plugin.min.js:4:1197
    at jR.<anonymous> (plugin.min.js:4:1412)
    at commands.exec.<computed> (tinymce.min.js:4:358670)
    at iR.execCommand (tinymce.min.js:4:358116)
    at jR.execCommand (tinymce.min.js:4:383782)
    at Object.onAction (plugin.min.js:4:842)`

This prevents updating the description field on any item. The biography field seems to work fine even though the code for the two appears to be the same. As far as I can tell there are no other issues with the system in v10, just lots of deprecation warnings due to the data structure change.

**Comment by wintersleepAI** [comment]
have you tried the 1.0 beta release? this should be fixed in there

https://github.com/wintersleepAI/foundry-swnr/releases/download/v1.0.0-wsAI-beta2/system.json 

(note I will drop an updated beta later today likely)

**Comment by Notaveerus** [comment]
Thanks that fixed the issue however the new sheet layout doesn't appear to have the custom resource tracking anymore

**Comment by wintersleepAI** [comment]
hopefully you saw the custom resource tracker is on the powers tab (need to update the text to reflect this).
