### ISSUE TITLE
Bestiary Attack Roll errors

### ISSUE THREAD

**Issue by icaruscoil** [wintersleepAI/foundry-swnr#44]
All NPCs in the Bestiary Compendium throw this error when an attack is made. Morale checks and other rolls work ok but not attack rolls. This is the same when rolled from locked compendium or imported to actors. Other compendium items appear to function normally, attacks with vehicles and ships roll normally.

Foundry VTT v10 b291  SWN v1.0.0  Active modules 0

\\\Uncaught (in promise) Error: Unresolved StringTerm none requested for evaluation 
    at StringTerm.evaluate (foundry.js:11730)
    at Roll._evaluate (foundry.js:9292)
    at Roll.evaluate (foundry.js:9256)
    at Roll.roll (foundry.js:9362)
    at SWNRWeapon.rollAttack (weapon.ts:115)
evaluate @ foundry.js:11730
_evaluate @ foundry.js:9292
evaluate @ foundry.js:9256
roll @ foundry.js:9362
rollAttack @ weapon.ts:115

**Comment by icaruscoil** [comment]
Uninstalled module and game, NPC attack rolls still fail. Noted migration errors in console on reinstallation:

Migration failed, 9 exceptions thrown for type SWNRBaseItem, version "0.4.0", sort 0
fetch @ foundry.js:59187
notify @ foundry.js:59114
error @ foundry.js:59150
checkAndRunMigrations @ migration.ts:82
async function (async)
checkAndRunMigrations @ migration.ts:58
(anonymous) @ swnr.ts:90
#call @ foundry.js:724
callAll @ foundry.js:681
setupGame @ foundry.js:7952
async function (async)
setupGame @ foundry.js:7916
_initializeGameView @ foundry.js:8999
_initializeView @ foundry.js:8975
initialize @ foundry.js:7825
async function (async)
initialize @ foundry.js:7816
window.addEventListener.once @ foundry.js:79693
async function (async)
window.addEventListener.once @ foundry.js:79692
migration.ts:83 Error: Migration failed, 9 exceptions thrown for type SWNRBaseItem, version "0.4.0", sort 0
    at checkAndRunMigrations (migration.ts:81)
checkAndRunMigrations @ migration.ts:83
async function (async)
checkAndRunMigrations @ migration.ts:58
(anonymous) @ swnr.ts:90
#call @ foundry.js:724
callAll @ foundry.js:681
setupGame @ foundry.js:7952
async function (async)
setupGame @ foundry.js:7916
_initializeGameView @ foundry.js:8999
_initializeView @ foundry.js:8975
initialize @ foundry.js:7825
async function (async)
initialize @ foundry.js:7816
window.addEventListener.once @ foundry.js:79693
async function (async)
window.addEventListener.once @ foundry.js:79692
foundry.js:59187 Migration failed, 9 exceptions thrown for type SWNRWeapon, version "0.4.0", sort 0
fetch @ foundry.js:59187
notify @ foundry.js:59114
error @ foundry.js:59150
checkAndRunMigrations @ migration.ts:82
async function (async)
checkAndRunMigrations @ migration.ts:58
(anonymous) @ swnr.ts:90
#call @ foundry.js:724
callAll @ foundry.js:681
setupGame @ foundry.js:7952
async function (async)
setupGame @ foundry.js:7916
_initializeGameView @ foundry.js:8999
_initializeView @ foundry.js:8975
initialize @ foundry.js:7825
async function (async)
initialize @ foundry.js:7816
window.addEventListener.once @ foundry.js:79693
async function (async)
window.addEventListener.once @ foundry.js:79692
migration.ts:83 Error: Migration failed, 9 exceptions thrown for type SWNRWeapon, version "0.4.0", sort 0
    at checkAndRunMigrations (migration.ts:81)
checkAndRunMigrations @ migration.ts:83
async function (async)
checkAndRunMigrations @ migration.ts:58
(anonymous) @ swnr.ts:90
#call @ foundry.js:724
callAll @ foundry.js:681
setupGame @ foundry.js:7952
async function (async)
setupGame @ foundry.js:7916
_initializeGameView @ foundry.js:8999
_initializeView @ foundry.js:8975
initialize @ foundry.js:7825
async function (async)
initialize @ foundry.js:7816
window.addEventListener.once @ foundry.js:79693
async function (async)
window.addEventListener.once @ foundry.js:79692

**Comment by icaruscoil** [comment]
Today I stood up a new linux server and installed the last build of v9 foundry.  
Same issue as before with NPC attacks, also created a new PC and gave him a gun and skills and it also errors.

Todd needs our help!
![Screenshot from 2023-02-27 17-05-42](https://user-images.githubusercontent.com/26393323/221726084-4beadbc9-1d58-41da-8b6e-3fc874c8b51c.png)


Uncaught (in promise) Error: Unresolved StringTerm none requested for evaluation
    evaluate foundry.js:9202
    _evaluate foundry.js:6811
    evaluate foundry.js:6778
    roll foundry.js:6878
    rollAttack weapon.ts:115
    roll weapon.ts:251
    _onWeaponRoll character-sheet.ts:388
    jQuery 8
    activateListeners character-sheet.ts:73
    _render foundry.js:3090
    _render foundry.js:3764
    render foundry.js:3021
    render foundry.js:4259
    render foundry.js:10819
    _onUpdateEmbeddedDocuments foundry.js:10948
    _onUpdateEmbeddedDocuments foundry.js:13799
    _handleUpdateEmbeddedDocuments foundry.js:10286
    _updateEmbeddedDocuments foundry.js:10163
    update backend.mjs:153
    updateDocuments document.mjs:373
    update document.mjs:456
    _updateObject foundry.js:4314
    _onSubmit foundry.js:3853
    _onChangeInput foundry.js:3901
    jQuery 8
        dispatch
        handle
        add
        Ee
        each
        each
        Ee
        on
    activateListeners foundry.js:3800
    activateListeners foundry.js:49545
    _render foundry.js:3090
    _render foundry.js:3764
    render foundry.js:3021
    render foundry.js:4259
    _onItemEdit actor-base-sheet.ts:242
    jQuery 6
        dispatch
        handle
        add
        Ee
        each
        each

**Comment by wintersleepAI** [comment]
this should be fixed with 1.0.1. holler if not. thanks!!
