### ISSUE TITLE
Update 11 seems completely incompatible with module

### ISSUE THREAD

**Issue by Novabella** [wintersleepAI/foundry-swnr#50]
Getting the message: 
"Error: Unable to load valid system manifest data from "https://github.com/wintersleepAI/foundry-swnr/releases.../system.json" System validation errors: packs: 27: type: may not be undefined 26: type: may not be undefined."

**Comment by Novabella** [comment]
I get the exact same error for v1.0.2

**Comment by wintersleepAI** [comment]
Yes no v11 support yet. I tried to mark 1.0.2 as compatible only w/10 but likely the older ones are not compatible either. Will see if there is something minimal to get it working.

**Comment by wintersleepAI** [comment]
just made 1.0.3 which allows the system to run in v11. likely some issues still. for example the search button does not work.
