### ISSUE TITLE
Foundry v12 compatibility

### ISSUE THREAD

**Issue by YunYun1337** [wintersleepAI/foundry-swnr#62]
I just started making a world after installing the latest foundry and have gone back to v11 to test it out, and in 11 interactions still work normally, but some things with the compendium interactions seems to have broken in v12. You can't open neither character sheets nor other objects/items that are part of the compendium.

**Comment by EisenhornPuritus** [comment]
I had the same problem (Migrated my campaign to V12 with the appropiate backups) and didn't manage to make it work. I'm back at V11 at the moment.

**Comment by wintersleepAI** [comment]
Currently doing a complete system re-write in native JS with help from a couple others. Using newer foundry frameworks so it should support up to v14.

**Comment by hanijajeh** [comment]
I am not a programmer, so I don't know what doing a complete system re-write means or the volume of work needed; I was wondering if I need to rollback to 11 or wait for the update.

another questions, do you have a patreon or another channel to show our support for you work.

thanks

**Comment by wintersleepAI** [comment]
You will want to rollback to v11 if you want to play SWN/CWN on foundry anytime soon. The rewrite means its a lot of work going on to make it ready for v12/13.

**Comment by wintersleepAI** [comment]
i have never opened a patreon or other means as i don't have the capacity to set up something with expectations on deliverables :)
