### ISSUE TITLE
Old Manifest Json links aren't updated with new updates.

### ISSUE THREAD

**Issue by Leolele99** [wintersleepAI/foundry-swnr#8]
It seems like to update this system one has to reinstall the system with the new json link provided in each new release.

Could a consistend, self updating json link be created so that the update button in foundry itself can be used?

**Comment by wintersleepAI** [comment]
This should be resolved with the release today. Would you be willing to test/confirm?

**Comment by Leolele99** [comment]
Works now, resolved :D

**Comment by wintersleepAI** [comment]
thanks for opening and closing the first issue!!!!
